# Generated by Django 4.2.1 on 2023-05-11 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comprador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('apellido', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256)),
                ('telefono', models.CharField(max_length=256)),
                ('direccion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Malla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('color', models.CharField(max_length=256)),
                ('talle', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Sombreros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('color', models.CharField(max_length=256)),
                ('talle', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256)),
                ('telefono', models.CharField(max_length=256)),
                ('direccion', models.TextField()),
                ('redes', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Vestidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('color', models.CharField(max_length=256)),
                ('talle', models.CharField(max_length=256)),
            ],
        ),
    ]
