# Generated by Django 4.2.1 on 2023-05-10 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaAnaRamona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vestidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('precio', models.IntegerField()),
                ('talle', models.CharField(max_length=256)),
            ],
        ),
        migrations.RenameModel(
            old_name='Producto',
            new_name='Malla',
        ),
    ]
