# Generated by Django 4.2.1 on 2023-05-11 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendaAnaRamona', '0002_vestidos_rename_producto_malla'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sombreros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('precio', models.IntegerField()),
                ('talle', models.CharField(max_length=256)),
            ],
        ),
    ]
